#!/bin/bash
npm install --registry=https://registry.npm.taobao.org
npm run build
if [ $? -eq 0 ]; then
  docker build -t reg.icity-os.com/smart-cityos/datav_center:1.0 .
  docker push reg.icity-os.com/smart-cityos/datav_center:1.0
else
  exit 1
fi